-- PALA v94: synkroniserede teltbemærkninger og systueopgaver.
-- Kør én gang i Supabase SQL Editor for projektet ywrkaiezqtgpckfxkgru.

begin;

create table if not exists public.tent_notes (
  tent_id bigint primary key references public.tents(id) on delete cascade,
  note text not null default '',
  updated_by_employee_id bigint references public.employees(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.tent_workshop_tasks (
  id bigint generated by default as identity primary key,
  tent_id bigint not null references public.tents(id) on delete cascade,
  booking_id bigint references public.bookings(id) on delete set null,
  description text not null,
  status text not null default 'open' check (status in ('open','completed')),
  completion_note text not null default '',
  created_by_employee_id bigint references public.employees(id) on delete set null,
  completed_by_employee_id bigint references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists tent_workshop_tasks_tent_status_idx
  on public.tent_workshop_tasks(tent_id, status, created_at desc);

alter table public.tent_notes enable row level security;
alter table public.tent_workshop_tasks enable row level security;
revoke all on public.tent_notes from anon, authenticated;
revoke all on public.tent_workshop_tasks from anon, authenticated;

create or replace function public.employee_tent_notes(p_token text)
returns table (
  tent_id bigint,
  note text,
  updated_by_employee_id bigint,
  updated_by_employee_name text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_employee record;
begin
  select * into v_employee from public.employee_validate(p_token) limit 1;
  if v_employee.employee_id is null then raise exception 'Ugyldig eller udløbet medarbejdersession'; end if;

  return query
  select n.tent_id, n.note, n.updated_by_employee_id, e.name, n.updated_at
  from public.tent_notes n
  left join public.employees e on e.id = n.updated_by_employee_id
  order by n.tent_id;
end;
$$;

create or replace function public.employee_save_tent_note(
  p_token text,
  p_tent_id bigint,
  p_note text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_employee record;
begin
  select * into v_employee from public.employee_validate(p_token) limit 1;
  if v_employee.employee_id is null then raise exception 'Ugyldig eller udløbet medarbejdersession'; end if;
  if not exists (select 1 from public.tents where id = p_tent_id) then raise exception 'Teltet findes ikke'; end if;

  if btrim(coalesce(p_note,'')) = '' then
    delete from public.tent_notes where tent_id = p_tent_id;
  else
    insert into public.tent_notes(tent_id, note, updated_by_employee_id, updated_at)
    values (p_tent_id, btrim(p_note), v_employee.employee_id, now())
    on conflict (tent_id) do update set
      note = excluded.note,
      updated_by_employee_id = excluded.updated_by_employee_id,
      updated_at = excluded.updated_at;
  end if;
end;
$$;

create or replace function public.employee_workshop_tasks(p_token text)
returns table (
  id bigint,
  tent_id bigint,
  tent_name text,
  booking_id bigint,
  booking_name text,
  description text,
  status text,
  completion_note text,
  created_by_employee_id bigint,
  created_by_employee_name text,
  completed_by_employee_id bigint,
  completed_by_employee_name text,
  created_at timestamptz,
  updated_at timestamptz,
  completed_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_employee record;
begin
  select * into v_employee from public.employee_validate(p_token) limit 1;
  if v_employee.employee_id is null then raise exception 'Ugyldig eller udløbet medarbejdersession'; end if;

  return query
  select w.id, w.tent_id, t.name, w.booking_id,
         coalesce(b.customer_name, b.title, b.order_no),
         w.description, w.status, w.completion_note,
         w.created_by_employee_id, created_by.name,
         w.completed_by_employee_id, completed_by.name,
         w.created_at, w.updated_at, w.completed_at
  from public.tent_workshop_tasks w
  join public.tents t on t.id = w.tent_id
  left join public.bookings b on b.id = w.booking_id
  left join public.employees created_by on created_by.id = w.created_by_employee_id
  left join public.employees completed_by on completed_by.id = w.completed_by_employee_id
  order by (w.status = 'open') desc, w.created_at desc, w.id desc;
end;
$$;

create or replace function public.employee_report_tent_damage(
  p_token text,
  p_tent_id bigint,
  p_booking_id bigint,
  p_description text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_employee record;
  v_id bigint;
begin
  select * into v_employee from public.employee_validate(p_token) limit 1;
  if v_employee.employee_id is null then raise exception 'Ugyldig eller udløbet medarbejdersession'; end if;
  if not exists (select 1 from public.tents where id = p_tent_id) then raise exception 'Teltet findes ikke'; end if;
  if p_booking_id is not null and not exists (select 1 from public.bookings where id = p_booking_id) then raise exception 'Ordren findes ikke'; end if;
  if btrim(coalesce(p_description,'')) = '' then raise exception 'Beskriv skaden'; end if;

  insert into public.tent_workshop_tasks(tent_id, booking_id, description, created_by_employee_id)
  values (p_tent_id, p_booking_id, btrim(p_description), v_employee.employee_id)
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.employee_set_workshop_task_status(
  p_token text,
  p_task_id bigint,
  p_completed boolean,
  p_completion_note text default ''
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_employee record;
begin
  select * into v_employee from public.employee_validate(p_token) limit 1;
  if v_employee.employee_id is null then raise exception 'Ugyldig eller udløbet medarbejdersession'; end if;

  update public.tent_workshop_tasks set
    status = case when p_completed then 'completed' else 'open' end,
    completion_note = case when p_completed then btrim(coalesce(p_completion_note,'')) else '' end,
    completed_by_employee_id = case when p_completed then v_employee.employee_id else null end,
    completed_at = case when p_completed then now() else null end,
    updated_at = now()
  where id = p_task_id;

  if not found then raise exception 'Systueopgaven findes ikke'; end if;
end;
$$;

revoke all on function public.employee_tent_notes(text) from public;
revoke all on function public.employee_save_tent_note(text,bigint,text) from public;
revoke all on function public.employee_workshop_tasks(text) from public;
revoke all on function public.employee_report_tent_damage(text,bigint,bigint,text) from public;
revoke all on function public.employee_set_workshop_task_status(text,bigint,boolean,text) from public;

grant execute on function public.employee_tent_notes(text) to anon, authenticated;
grant execute on function public.employee_save_tent_note(text,bigint,text) to anon, authenticated;
grant execute on function public.employee_workshop_tasks(text) to anon, authenticated;
grant execute on function public.employee_report_tent_damage(text,bigint,bigint,text) to anon, authenticated;
grant execute on function public.employee_set_workshop_task_status(text,bigint,boolean,text) to anon, authenticated;

commit;
