-- PALA v95 · komplet databaseopsætning til et tomt Supabase-projekt.
-- Kør filen én gang i SQL Editor før pala_v95_seed.sql.

begin;

create extension if not exists pgcrypto;

create table if not exists public.tents (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  stock_count integer,
  area_m2 numeric,
  diameter_m numeric,
  length_m numeric,
  width_m numeric,
  side_height_m numeric,
  ridge_height_m numeric,
  side_sections text,
  list_price_ex_vat numeric,
  source_tent_no text,
  source_page text,
  source_notes text,
  tent_image text,
  drawing_image text,
  return_note text,
  updated_at timestamptz not null default now()
);

create table if not exists public.hardware (
  id bigint generated by default as identity primary key,
  tent_id bigint not null references public.tents(id) on delete cascade,
  name text not null,
  description text not null default '',
  qty integer not null default 1 check (qty >= 0),
  packed integer not null default 0,
  image text,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Inventar',
  description text not null default '',
  quantity_total integer,
  image text,
  updated_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  order_no text,
  customer_name text,
  title text,
  start_date date not null,
  end_date date not null,
  delivery_date date,
  pickup_date date,
  status text not null default 'På lager',
  color text not null default '#5B7FBE',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create table if not exists public.booking_tents (
  booking_id bigint not null references public.bookings(id) on delete cascade,
  tent_id bigint not null references public.tents(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  primary key (booking_id, tent_id)
);

create table if not exists public.booking_inventory (
  booking_id bigint not null references public.bookings(id) on delete cascade,
  inventory_id bigint not null references public.inventory(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  primary key (booking_id, inventory_id)
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  is_admin boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_credentials (
  employee_id bigint primary key references public.employees(id) on delete cascade,
  pin_hash text not null,
  failed_login_attempts integer not null default 0,
  locked_until timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_sessions (
  token text primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days')
);

create table if not exists public.staffing_shifts (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete cascade,
  shift_date date not null,
  start_time time,
  end_time time,
  workers_needed integer not null default 1 check (workers_needed > 0),
  title text not null default 'Vagt',
  notes text not null default '',
  daily_leader_employee_id bigint references public.employees(id) on delete set null,
  created_by_employee_id bigint references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.staffing_assignments (
  id bigint generated by default as identity primary key,
  shift_id bigint not null references public.staffing_shifts(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (shift_id, employee_id)
);

create table if not exists public.staffing_invitations (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete cascade,
  shift_id bigint not null references public.staffing_shifts(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  created_by_employee_id bigint references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  unique (shift_id, employee_id)
);

create table if not exists public.tent_documents (
  id bigint generated by default as identity primary key,
  tent_id bigint not null references public.tents(id) on delete cascade,
  title text not null,
  file_name text,
  mime_type text,
  file_data text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tent_images (
  id bigint generated by default as identity primary key,
  tent_id bigint not null references public.tents(id) on delete cascade,
  caption text not null default '',
  image_data text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tent_notes (
  tent_id bigint primary key references public.tents(id) on delete cascade,
  note text not null default '',
  updated_by_employee_id bigint references public.employees(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.tent_workshop_tasks (
  id bigint generated by default as identity primary key,
  tent_id bigint not null references public.tents(id) on delete cascade,
  booking_id bigint references public.bookings(id) on delete set null,
  description text not null,
  status text not null default 'open' check (status in ('open','completed')),
  completion_note text not null default '',
  created_by_employee_id bigint references public.employees(id) on delete set null,
  completed_by_employee_id bigint references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.tent_wet_status (
  tent_id bigint primary key references public.tents(id) on delete cascade,
  wet_tents integer not null default 0 check (wet_tents >= 0),
  wet_sides integer not null default 0 check (wet_sides >= 0),
  updated_by_employee_id bigint references public.employees(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.order_access_tokens (
  token text primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '14 days')
);

create table if not exists public.order_checklist_progress (
  booking_id bigint not null references public.bookings(id) on delete cascade,
  line_type text not null check (line_type in ('tent','hardware','inventory')),
  item_id bigint not null,
  parent_tent_id bigint not null default 0,
  packed_qty integer not null default 0 check (packed_qty >= 0),
  returned_qty integer not null default 0 check (returned_qty >= 0),
  drying_required_qty integer not null default 0 check (drying_required_qty >= 0),
  dried_qty integer not null default 0 check (dried_qty >= 0),
  updated_at timestamptz not null default now(),
  primary key (booking_id, line_type, item_id, parent_tent_id)
);

create index if not exists bookings_period_idx on public.bookings(start_date, end_date);
create index if not exists shifts_date_idx on public.staffing_shifts(shift_date, start_time);
create index if not exists assignments_shift_idx on public.staffing_assignments(shift_id);
create index if not exists invitations_employee_idx on public.staffing_invitations(employee_id, status, created_at desc);
create index if not exists workshop_status_idx on public.tent_workshop_tasks(status, created_at desc);

create or replace function public.pala_session_employee(p_token text)
returns table(employee_id bigint, employee_name text, is_admin boolean)
language sql
security definer
set search_path = public, pg_temp
as $$
  select e.id, e.name, e.is_admin
  from public.employee_sessions s
  join public.employees e on e.id = s.employee_id
  where s.token = p_token and s.expires_at > now() and e.active = true
  limit 1
$$;

create or replace function public.employee_validate(p_token text)
returns table(token text, employee_id bigint, employee_name text, is_admin boolean, expires_at timestamptz)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from public.employee_sessions where expires_at <= now();
  update public.employee_sessions set expires_at = greatest(expires_at, now() + interval '30 days') where employee_sessions.token = p_token;
  return query
  select s.token, e.id, e.name, e.is_admin, s.expires_at
  from public.employee_sessions s join public.employees e on e.id = s.employee_id
  where s.token = p_token and s.expires_at > now() and e.active = true limit 1;
end;
$$;

create or replace function public.employee_login(p_employee_id bigint, p_pin text)
returns table(token text, employee_id bigint, employee_name text, is_admin boolean, expires_at timestamptz)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_employee public.employees%rowtype; v_credential public.employee_credentials%rowtype; v_token text; v_expires timestamptz;
begin
  select * into v_employee from public.employees where id = p_employee_id and active = true for update;
  if v_employee.id is null then return; end if;
  select c.* into v_credential from public.employee_credentials c where c.employee_id=p_employee_id;
  if v_credential.pin_hash is null or extensions.crypt(coalesce(p_pin,''), v_credential.pin_hash) <> v_credential.pin_hash then
    return;
  end if;
  v_token := gen_random_uuid()::text; v_expires := now() + interval '30 days';
  insert into public.employee_sessions(token,employee_id,expires_at) values(v_token,p_employee_id,v_expires);
  return query select v_token, v_employee.id, v_employee.name, v_employee.is_admin, v_expires;
end;
$$;

create or replace function public.employee_logout(p_token text)
returns void language sql security definer set search_path = public, pg_temp
as $$ delete from public.employee_sessions where token = p_token $$;

create or replace function public.inventory_catalog_v1()
returns setof public.inventory
language sql security definer set search_path = public, pg_temp
as $$ select * from public.inventory order by name $$;

create or replace function public.employee_change_own_pin(p_token text, p_current_pin text, p_new_pin text)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_id bigint; v_hash text;
begin
  select s.employee_id into v_id from public.employee_sessions s join public.employees e on e.id=s.employee_id where s.token=p_token and s.expires_at>now() and e.active limit 1;
  if v_id is null then raise exception 'Ugyldig eller udløbet medarbejdersession'; end if;
  if p_new_pin !~ '^[0-9]{4,8}$' then raise exception 'Den nye kode skal være 4-8 cifre'; end if;
  select pin_hash into v_hash from public.employee_credentials where employee_id=v_id;
  if extensions.crypt(coalesce(p_current_pin,''),v_hash) <> v_hash then raise exception 'Den nuværende kode er forkert'; end if;
  update public.employee_credentials set pin_hash=extensions.crypt(p_new_pin,extensions.gen_salt('bf')),updated_at=now() where employee_id=v_id;
  delete from public.employee_sessions where employee_id=v_id and token<>p_token;
end;
$$;

create or replace function public.admin_save_employee(p_token text, p_id bigint, p_name text, p_is_admin boolean)
returns bigint
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_admin record; v_id bigint; v_can_manage_admin boolean;
begin
  select * into v_admin from public.pala_session_employee(p_token) limit 1;
  if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if;
  v_can_manage_admin := lower(btrim(v_admin.employee_name))='lukas';
  if btrim(coalesce(p_name,''))='' then raise exception 'Medarbejderen skal have et navn'; end if;
  if p_id is null then
    insert into public.employees(name,is_admin,sort_order)
    values(btrim(p_name),case when v_can_manage_admin then coalesce(p_is_admin,false) else false end,(select coalesce(max(sort_order),0)+1 from public.employees))
    returning id into v_id;
    insert into public.employee_credentials(employee_id,pin_hash) values(v_id,extensions.crypt('4211',extensions.gen_salt('bf')));
  else
    if not exists(select 1 from public.employees where id=p_id) then raise exception 'Medarbejderen findes ikke'; end if;
    if v_can_manage_admin then
      if p_id=v_admin.employee_id and coalesce(p_is_admin,false)=false then raise exception 'Lukas kan ikke fjerne sin egen adminstatus'; end if;
      update public.employees set name=btrim(p_name),is_admin=coalesce(p_is_admin,false),updated_at=now() where id=p_id;
    else
      update public.employees set name=btrim(p_name),updated_at=now() where id=p_id;
    end if;
    v_id:=p_id;
  end if;
  return v_id;
end;
$$;

create or replace function public.admin_change_employee_pin(p_token text, p_employee_id bigint, p_pin text)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_admin record;
begin
  select * into v_admin from public.pala_session_employee(p_token) limit 1;
  if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if;
  if p_pin !~ '^[0-9]{4,8}$' then raise exception 'Koden skal være 4-8 cifre'; end if;
  update public.employee_credentials set pin_hash=extensions.crypt(p_pin,extensions.gen_salt('bf')),failed_login_attempts=0,locked_until=null,updated_at=now() where employee_id=p_employee_id;
  if not found then raise exception 'Medarbejderen findes ikke'; end if;
  delete from public.employee_sessions where employee_id=p_employee_id and token<>p_token;
end;
$$;

create or replace function public.admin_delete_employee(p_token text, p_id bigint)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_admin record; v_target_admin boolean;
begin
  select * into v_admin from public.pala_session_employee(p_token) limit 1;
  if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if;
  if p_id=v_admin.employee_id then raise exception 'Du kan ikke slette dig selv'; end if;
  select is_admin into v_target_admin from public.employees where id=p_id;
  if coalesce(v_target_admin,false) and lower(btrim(v_admin.employee_name))<>'lukas' then raise exception 'Kun Lukas kan fjerne en administrator'; end if;
  delete from public.employees where id=p_id;
end;
$$;

create or replace function public.admin_save_booking(
  p_token text,p_id bigint,p_order_no text,p_customer_name text,p_title text,p_start_date date,p_end_date date,
  p_delivery_date date,p_pickup_date date,p_status text,p_color text,p_notes text,p_tents jsonb,p_inventory jsonb
)
returns bigint
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_admin record; v_id bigint;
begin
  select * into v_admin from public.pala_session_employee(p_token) limit 1;
  if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if;
  if p_start_date is null or p_end_date is null or p_end_date<p_start_date then raise exception 'Kontrollér brugsperioden'; end if;
  if p_id is null then
    insert into public.bookings(order_no,customer_name,title,start_date,end_date,delivery_date,pickup_date,status,color,notes)
    values(nullif(btrim(p_order_no),''),nullif(btrim(p_customer_name),''),nullif(btrim(p_title),''),p_start_date,p_end_date,p_delivery_date,p_pickup_date,coalesce(nullif(p_status,''),'På lager'),coalesce(nullif(p_color,''),'#5B7FBE'),coalesce(p_notes,'')) returning id into v_id;
  else
    update public.bookings set order_no=nullif(btrim(p_order_no),''),customer_name=nullif(btrim(p_customer_name),''),title=nullif(btrim(p_title),''),start_date=p_start_date,end_date=p_end_date,delivery_date=p_delivery_date,pickup_date=p_pickup_date,status=coalesce(nullif(p_status,''),'På lager'),color=coalesce(nullif(p_color,''),'#5B7FBE'),notes=coalesce(p_notes,''),updated_at=now() where id=p_id;
    if not found then raise exception 'Ordren findes ikke'; end if; v_id:=p_id;
  end if;
  delete from public.booking_tents where booking_id=v_id;
  insert into public.booking_tents(booking_id,tent_id,quantity)
  select v_id,x.tent_id,greatest(1,coalesce(x.quantity,1)) from jsonb_to_recordset(coalesce(p_tents,'[]'::jsonb)) as x(tent_id bigint,quantity integer)
  where exists(select 1 from public.tents t where t.id=x.tent_id);
  delete from public.booking_inventory where booking_id=v_id;
  insert into public.booking_inventory(booking_id,inventory_id,quantity)
  select v_id,x.inventory_id,greatest(1,coalesce(x.quantity,1)) from jsonb_to_recordset(coalesce(p_inventory,'[]'::jsonb)) as x(inventory_id bigint,quantity integer)
  where exists(select 1 from public.inventory i where i.id=x.inventory_id);
  return v_id;
end;
$$;

create or replace function public.admin_delete_booking(p_token text,p_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; begin select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if; delete from public.bookings where id=p_id; end $$;

create or replace function public.admin_finish_booking(p_token text,p_booking_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; begin select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if; update public.bookings set status='Afsluttet',updated_at=now() where id=p_booking_id; if not found then raise exception 'Ordren findes ikke'; end if; end $$;

create or replace function public.admin_save_shift_v2(
  p_token text,p_id bigint,p_booking_id bigint,p_shift_date date,p_start_time time,p_end_time time,p_workers_needed integer,p_title text,p_notes text,p_daily_leader_employee_id bigint
)
returns bigint
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_admin record; v_id bigint;
begin
  select * into v_admin from public.pala_session_employee(p_token) limit 1;
  if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if;
  if p_shift_date is null then raise exception 'Vælg dato for vagten'; end if;
  if p_id is null then
    insert into public.staffing_shifts(booking_id,shift_date,start_time,end_time,workers_needed,title,notes,daily_leader_employee_id,created_by_employee_id)
    values(p_booking_id,p_shift_date,p_start_time,p_end_time,greatest(1,coalesce(p_workers_needed,1)),coalesce(nullif(btrim(p_title),''),'Vagt'),coalesce(p_notes,''),p_daily_leader_employee_id,v_admin.employee_id) returning id into v_id;
  else
    update public.staffing_shifts set booking_id=p_booking_id,shift_date=p_shift_date,start_time=p_start_time,end_time=p_end_time,workers_needed=greatest(1,coalesce(p_workers_needed,1)),title=coalesce(nullif(btrim(p_title),''),'Vagt'),notes=coalesce(p_notes,''),daily_leader_employee_id=p_daily_leader_employee_id,updated_at=now() where id=p_id;
    if not found then raise exception 'Vagten findes ikke'; end if; v_id:=p_id;
  end if;
  if p_daily_leader_employee_id is not null then insert into public.staffing_assignments(shift_id,employee_id) values(v_id,p_daily_leader_employee_id) on conflict do nothing; end if;
  return v_id;
end;
$$;

create or replace function public.admin_delete_shift(p_token text,p_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; begin select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if; delete from public.staffing_shifts where id=p_id; end $$;

create or replace function public.employee_staff_signup(p_token text,p_shift_id bigint)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1;
  if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  if not exists(select 1 from public.staffing_shifts where id=p_shift_id) then raise exception 'Vagten findes ikke'; end if;
  insert into public.staffing_assignments(shift_id,employee_id) values(p_shift_id,v_employee.employee_id) on conflict do nothing;
  update public.staffing_invitations set status='accepted',responded_at=now() where shift_id=p_shift_id and employee_id=v_employee.employee_id;
end $$;

create or replace function public.employee_staff_signoff(p_token text,p_shift_id bigint)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1;
  if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  delete from public.staffing_assignments where shift_id=p_shift_id and employee_id=v_employee.employee_id;
end $$;

create or replace function public.admin_invite_staffing(p_token text,p_shift_id bigint,p_employee_ids jsonb)
returns integer
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_admin record; v_booking_id bigint; v_count integer;
begin
  select * into v_admin from public.pala_session_employee(p_token) limit 1;
  if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if;
  select booking_id into v_booking_id from public.staffing_shifts where id=p_shift_id;
  if not found then raise exception 'Vagten findes ikke'; end if;
  insert into public.staffing_invitations(booking_id,shift_id,employee_id,status,created_by_employee_id)
  select v_booking_id,p_shift_id,(value #>> '{}')::bigint,'pending',v_admin.employee_id from jsonb_array_elements(coalesce(p_employee_ids,'[]'::jsonb))
  where exists(select 1 from public.employees e where e.id=(value #>> '{}')::bigint and e.active)
  on conflict(shift_id,employee_id) do update set status='pending',created_by_employee_id=excluded.created_by_employee_id,created_at=now(),responded_at=null;
  get diagnostics v_count=row_count; return v_count;
end;
$$;

create or replace function public.employee_staffing_invitations(p_token text)
returns table(id bigint,booking_id bigint,shift_id bigint,status text,created_at timestamptz,shift_date date,start_time time,end_time time,shift_title text,workers_needed integer,booking_name text,booking_color text)
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1;
  if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  return query select i.id,i.booking_id,i.shift_id,i.status,i.created_at,s.shift_date,s.start_time,s.end_time,s.title,s.workers_needed,coalesce(b.customer_name,b.title,b.order_no,'Job'),coalesce(b.color,'#5B7FBE')
  from public.staffing_invitations i join public.staffing_shifts s on s.id=i.shift_id left join public.bookings b on b.id=i.booking_id
  where i.employee_id=v_employee.employee_id order by (i.status='pending') desc,s.shift_date,i.created_at desc;
end $$;

create or replace function public.employee_respond_staffing_invitation(p_token text,p_invitation_id bigint,p_accept boolean)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; v_shift bigint; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1;
  if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  select shift_id into v_shift from public.staffing_invitations where id=p_invitation_id and employee_id=v_employee.employee_id for update;
  if v_shift is null then raise exception 'Forespørgslen findes ikke'; end if;
  update public.staffing_invitations set status=case when p_accept then 'accepted' else 'declined' end,responded_at=now() where id=p_invitation_id;
  if p_accept then insert into public.staffing_assignments(shift_id,employee_id) values(v_shift,v_employee.employee_id) on conflict do nothing; end if;
end $$;

create or replace function public.admin_save_tent_v2(
  p_token text,p_id bigint,p_name text,p_description text,p_stock_count integer,p_area_m2 numeric,p_diameter_m numeric,
  p_length_m numeric,p_width_m numeric,p_side_height_m numeric,p_ridge_height_m numeric,p_hardware jsonb
)
returns bigint
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_admin record; v_id bigint;
begin
  select * into v_admin from public.pala_session_employee(p_token) limit 1;
  if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if;
  if btrim(coalesce(p_name,''))='' then raise exception 'Teltet skal have et navn'; end if;
  if p_id is null then
    insert into public.tents(name,description,stock_count,area_m2,diameter_m,length_m,width_m,side_height_m,ridge_height_m)
    values(btrim(p_name),coalesce(p_description,''),p_stock_count,p_area_m2,p_diameter_m,p_length_m,p_width_m,p_side_height_m,p_ridge_height_m) returning id into v_id;
  else
    update public.tents set name=btrim(p_name),description=coalesce(p_description,''),stock_count=p_stock_count,area_m2=p_area_m2,diameter_m=p_diameter_m,length_m=p_length_m,width_m=p_width_m,side_height_m=p_side_height_m,ridge_height_m=p_ridge_height_m,updated_at=now() where id=p_id;
    if not found then raise exception 'Teltet findes ikke'; end if; v_id:=p_id;
  end if;
  delete from public.hardware where tent_id=v_id;
  insert into public.hardware(id,tent_id,name,description,qty,sort_order)
  select x.id,v_id,btrim(x.name),coalesce(x.description,''),greatest(0,coalesce(x.qty,1)),coalesce(x.sort_order,0)
  from jsonb_to_recordset(coalesce(p_hardware,'[]'::jsonb)) as x(id bigint,name text,description text,qty integer,sort_order integer)
  where btrim(coalesce(x.name,''))<>'' and x.id is not null;
  insert into public.hardware(tent_id,name,description,qty,sort_order)
  select v_id,btrim(x.name),coalesce(x.description,''),greatest(0,coalesce(x.qty,1)),coalesce(x.sort_order,0)
  from jsonb_to_recordset(coalesce(p_hardware,'[]'::jsonb)) as x(id bigint,name text,description text,qty integer,sort_order integer)
  where btrim(coalesce(x.name,''))<>'' and x.id is null;
  return v_id;
end;
$$;

create or replace function public.admin_delete_tent(p_token text,p_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; begin select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if; delete from public.tents where id=p_id; end $$;

create or replace function public.admin_save_inventory_v2(p_token text,p_id bigint,p_category text,p_name text,p_description text,p_quantity_total integer,p_image text)
returns bigint
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_admin record; v_id bigint;
begin
  select * into v_admin from public.pala_session_employee(p_token) limit 1;
  if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if;
  if btrim(coalesce(p_name,''))='' then raise exception 'Inventaret skal have et navn'; end if;
  if p_id is null then insert into public.inventory(name,category,description,quantity_total,image) values(btrim(p_name),'Inventar',coalesce(p_description,''),greatest(0,coalesce(p_quantity_total,0)),coalesce(p_image,'')) returning id into v_id;
  else update public.inventory set name=btrim(p_name),category='Inventar',description=coalesce(p_description,''),quantity_total=greatest(0,coalesce(p_quantity_total,0)),image=coalesce(p_image,image),updated_at=now() where id=p_id returning id into v_id; end if;
  if v_id is null then raise exception 'Inventaret findes ikke'; end if; return v_id;
end;
$$;

create or replace function public.admin_delete_inventory(p_token text,p_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; begin select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if; delete from public.inventory where id=p_id; end $$;

create or replace function public.admin_add_tent_image(p_token text,p_tent_id bigint,p_caption text,p_image_data text)
returns bigint language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; v_id bigint; begin select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if; insert into public.tent_images(tent_id,caption,image_data) values(p_tent_id,coalesce(p_caption,''),p_image_data) returning id into v_id; return v_id; end $$;

create or replace function public.admin_delete_tent_image(p_token text,p_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; begin select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if; delete from public.tent_images where id=p_id; end $$;

create or replace function public.admin_add_tent_document(p_token text,p_tent_id bigint,p_title text,p_file_name text,p_mime_type text,p_file_data text)
returns bigint language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; v_id bigint; begin select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if; insert into public.tent_documents(tent_id,title,file_name,mime_type,file_data) values(p_tent_id,btrim(p_title),p_file_name,p_mime_type,p_file_data) returning id into v_id; return v_id; end $$;

create or replace function public.admin_delete_tent_document(p_token text,p_id bigint)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; begin select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if; delete from public.tent_documents where id=p_id; end $$;

create or replace function public.employee_mark_tent_wet(p_token text,p_tent_id bigint)
returns integer
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; v_total integer; v_value integer; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  select greatest(1,coalesce(stock_count,1)) into v_total from public.tents where id=p_tent_id; if v_total is null then raise exception 'Teltet findes ikke'; end if;
  insert into public.tent_wet_status(tent_id,wet_tents,updated_by_employee_id) values(p_tent_id,1,v_employee.employee_id)
  on conflict(tent_id) do update set wet_tents=least(v_total,public.tent_wet_status.wet_tents+1),updated_by_employee_id=v_employee.employee_id,updated_at=now()
  returning wet_tents into v_value; return v_value;
end $$;

create or replace function public.employee_clear_tent_wet(p_token text,p_tent_id bigint)
returns integer
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; v_value integer; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  update public.tent_wet_status set wet_tents=greatest(0,wet_tents-1),updated_by_employee_id=v_employee.employee_id,updated_at=now() where tent_id=p_tent_id returning wet_tents into v_value;
  return coalesce(v_value,0);
end $$;

create or replace function public.employee_mark_tent_sides_wet(p_token text,p_tent_id bigint)
returns integer
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; v_value integer; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  if not exists(select 1 from public.tents where id=p_tent_id) then raise exception 'Teltet findes ikke'; end if;
  insert into public.tent_wet_status(tent_id,wet_sides,updated_by_employee_id) values(p_tent_id,1,v_employee.employee_id)
  on conflict(tent_id) do update set wet_sides=public.tent_wet_status.wet_sides+1,updated_by_employee_id=v_employee.employee_id,updated_at=now()
  returning wet_sides into v_value; return v_value;
end $$;

create or replace function public.employee_clear_tent_sides_wet(p_token text,p_tent_id bigint)
returns integer
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; v_value integer; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  update public.tent_wet_status set wet_sides=greatest(0,wet_sides-1),updated_by_employee_id=v_employee.employee_id,updated_at=now() where tent_id=p_tent_id returning wet_sides into v_value;
  return coalesce(v_value,0);
end $$;

create or replace function public.admin_clear_tent_drying(p_token text,p_tent_id bigint,p_qty integer)
returns integer
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_admin record; v_value integer; begin
  select * into v_admin from public.pala_session_employee(p_token) limit 1; if v_admin.employee_id is null or not v_admin.is_admin then raise exception 'Administratorlogin kræves'; end if;
  update public.tent_wet_status set wet_tents=case when p_qty is null then 0 else greatest(0,wet_tents-greatest(0,p_qty)) end,updated_by_employee_id=v_admin.employee_id,updated_at=now() where tent_id=p_tent_id returning wet_tents into v_value;
  return coalesce(v_value,0);
end $$;

create or replace function public.pala_order_lines(p_booking_id bigint)
returns table(id bigint,line_type text,item_id bigint,parent_tent_id bigint,item_name text,description text,qty_required integer)
language sql stable security definer set search_path = public, pg_temp
as $$
  select p_booking_id*1000000+100000+t.id,'tent',t.id,0,t.name,t.description,bt.quantity
  from public.booking_tents bt join public.tents t on t.id=bt.tent_id where bt.booking_id=p_booking_id
  union all
  select p_booking_id*1000000+200000+h.id,'hardware',h.id,t.id,h.name,coalesce(nullif(h.description,''),'Til '||t.name),bt.quantity*h.qty
  from public.booking_tents bt join public.tents t on t.id=bt.tent_id join public.hardware h on h.tent_id=t.id where bt.booking_id=p_booking_id
  union all
  select p_booking_id*1000000+300000+i.id,'inventory',i.id,0,i.name,i.description,bi.quantity
  from public.booking_inventory bi join public.inventory i on i.id=bi.inventory_id where bi.booking_id=p_booking_id
$$;

create or replace function public.employee_order_check_token(p_token text,p_booking_id bigint)
returns text
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; v_token text; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  if not exists(select 1 from public.bookings where id=p_booking_id) then raise exception 'Ordren findes ikke'; end if;
  v_token:=gen_random_uuid()::text; insert into public.order_access_tokens(token,booking_id,employee_id) values(v_token,p_booking_id,v_employee.employee_id); return v_token;
end $$;

create or replace function public.order_checklist_get(p_access_token text)
returns jsonb
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_booking_id bigint; v_order jsonb; v_lines jsonb;
begin
  select booking_id into v_booking_id from public.order_access_tokens where token=p_access_token and expires_at>now();
  if v_booking_id is null then raise exception 'Pakkelinket er ugyldigt eller udløbet'; end if;
  select to_jsonb(b) into v_order from public.bookings b where b.id=v_booking_id;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',l.id,'line_type',l.line_type,'item_id',l.item_id,'parent_tent_id',nullif(l.parent_tent_id,0),'item_name',l.item_name,'description',l.description,'qty_required',l.qty_required,
    'packed_qty',least(l.qty_required,coalesce(p.packed_qty,0)),'returned_qty',least(l.qty_required,coalesce(p.returned_qty,0)),
    'drying_required_qty',case when l.line_type='tent' then least(l.qty_required,coalesce(p.drying_required_qty,0)) else 0 end,
    'dried_qty',case when l.line_type='tent' then least(l.qty_required,coalesce(p.dried_qty,0)) else 0 end
  ) order by case l.line_type when 'tent' then 1 when 'hardware' then 2 else 3 end,l.parent_tent_id,l.item_name),'[]'::jsonb)
  into v_lines from public.pala_order_lines(v_booking_id) l left join public.order_checklist_progress p on p.booking_id=v_booking_id and p.line_type=l.line_type and p.item_id=l.item_id and p.parent_tent_id=l.parent_tent_id;
  return jsonb_build_object('order',v_order,'lines',v_lines);
end $$;

create or replace function public.order_checklist_change(p_access_token text,p_line_id bigint,p_phase text,p_delta integer,p_set_all boolean)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_booking_id bigint; v_line record; v_packed integer; v_returned integer;
begin
  select booking_id into v_booking_id from public.order_access_tokens where token=p_access_token and expires_at>now(); if v_booking_id is null then raise exception 'Pakkelinket er ugyldigt eller udløbet'; end if;
  select * into v_line from public.pala_order_lines(v_booking_id) where id=p_line_id; if v_line.id is null then raise exception 'Linjen findes ikke'; end if;
  select coalesce(packed_qty,0),coalesce(returned_qty,0) into v_packed,v_returned from public.order_checklist_progress where booking_id=v_booking_id and line_type=v_line.line_type and item_id=v_line.item_id and parent_tent_id=v_line.parent_tent_id;
  if p_phase='returned' then v_returned:=case when p_set_all then v_line.qty_required else greatest(0,least(v_line.qty_required,coalesce(v_returned,0)+coalesce(p_delta,0))) end; v_packed:=greatest(coalesce(v_packed,0),v_returned);
  elsif p_phase='packed' then v_packed:=case when p_set_all then v_line.qty_required else greatest(v_returned,least(v_line.qty_required,coalesce(v_packed,0)+coalesce(p_delta,0))) end;
  else raise exception 'Ukendt pakkefase'; end if;
  insert into public.order_checklist_progress(booking_id,line_type,item_id,parent_tent_id,packed_qty,returned_qty)
  values(v_booking_id,v_line.line_type,v_line.item_id,v_line.parent_tent_id,v_packed,v_returned)
  on conflict(booking_id,line_type,item_id,parent_tent_id) do update set packed_qty=excluded.packed_qty,returned_qty=excluded.returned_qty,updated_at=now();
end $$;

create or replace function public.order_checklist_set_drying(p_access_token text,p_line_id bigint,p_delta integer,p_set_all boolean)
returns void
language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_booking_id bigint; v_employee_id bigint; v_line record; v_drying integer;
begin
  select booking_id,employee_id into v_booking_id,v_employee_id from public.order_access_tokens where token=p_access_token and expires_at>now(); if v_booking_id is null then raise exception 'Pakkelinket er ugyldigt eller udløbet'; end if;
  select * into v_line from public.pala_order_lines(v_booking_id) where id=p_line_id and line_type='tent'; if v_line.id is null then raise exception 'Teltlinjen findes ikke'; end if;
  select coalesce(drying_required_qty,0) into v_drying from public.order_checklist_progress where booking_id=v_booking_id and line_type='tent' and item_id=v_line.item_id and parent_tent_id=0;
  v_drying:=case when p_set_all then v_line.qty_required else greatest(0,least(v_line.qty_required,coalesce(v_drying,0)+coalesce(p_delta,0))) end;
  insert into public.order_checklist_progress(booking_id,line_type,item_id,parent_tent_id,drying_required_qty) values(v_booking_id,'tent',v_line.item_id,0,v_drying)
  on conflict(booking_id,line_type,item_id,parent_tent_id) do update set drying_required_qty=excluded.drying_required_qty,updated_at=now();
  insert into public.tent_wet_status(tent_id,wet_tents,updated_by_employee_id) values(v_line.item_id,v_drying,v_employee_id)
  on conflict(tent_id) do update set wet_tents=greatest(public.tent_wet_status.wet_tents,v_drying),updated_by_employee_id=v_employee_id,updated_at=now();
end $$;

create or replace function public.warehouse_stock_status_v2()
returns table(item_type text,item_id bigint,total_qty integer,out_qty integer,drying_qty integer,wet_sides_qty integer)
language sql stable security definer set search_path = public, pg_temp
as $$
  select 'tent',t.id,greatest(0,coalesce(t.stock_count,1)),
    coalesce((select sum(bt.quantity)::integer from public.booking_tents bt join public.bookings b on b.id=bt.booking_id where bt.tent_id=t.id and b.status in ('Ude','Udleveret')),0),
    coalesce(w.wet_tents,0),coalesce(w.wet_sides,0)
  from public.tents t left join public.tent_wet_status w on w.tent_id=t.id
  union all
  select 'hardware',h.id,greatest(0,h.qty*coalesce(t.stock_count,1)),
    coalesce((select sum(bt.quantity*h.qty)::integer from public.booking_tents bt join public.bookings b on b.id=bt.booking_id where bt.tent_id=h.tent_id and b.status in ('Ude','Udleveret')),0),0,0
  from public.hardware h join public.tents t on t.id=h.tent_id
  union all
  select 'inventory',i.id,greatest(0,coalesce(i.quantity_total,0)),
    coalesce((select sum(bi.quantity)::integer from public.booking_inventory bi join public.bookings b on b.id=bi.booking_id where bi.inventory_id=i.id and b.status in ('Ude','Udleveret')),0),0,0
  from public.inventory i
$$;

create or replace function public.booking_checklist_summaries()
returns table(booking_id bigint,hardware_total integer,hardware_packed integer,tent_total integer,tent_packed integer,inventory_total integer,inventory_packed integer,total_required integer,total_packed integer,total_returned integer)
language sql stable security definer set search_path = public, pg_temp
as $$
  select b.id,
    coalesce(sum(l.qty_required) filter(where l.line_type='hardware'),0)::integer,
    coalesce(sum(least(l.qty_required,coalesce(p.packed_qty,0))) filter(where l.line_type='hardware'),0)::integer,
    coalesce(sum(l.qty_required) filter(where l.line_type='tent'),0)::integer,
    coalesce(sum(least(l.qty_required,coalesce(p.packed_qty,0))) filter(where l.line_type='tent'),0)::integer,
    coalesce(sum(l.qty_required) filter(where l.line_type='inventory'),0)::integer,
    coalesce(sum(least(l.qty_required,coalesce(p.packed_qty,0))) filter(where l.line_type='inventory'),0)::integer,
    coalesce(sum(l.qty_required),0)::integer,
    coalesce(sum(least(l.qty_required,coalesce(p.packed_qty,0))),0)::integer,
    coalesce(sum(least(l.qty_required,coalesce(p.returned_qty,0))),0)::integer
  from public.bookings b
  left join lateral public.pala_order_lines(b.id) l on true
  left join public.order_checklist_progress p on p.booking_id=b.id and p.line_type=l.line_type and p.item_id=l.item_id and p.parent_tent_id=l.parent_tent_id
  group by b.id order by b.id
$$;

create or replace function public.employee_tent_notes(p_token text)
returns table(tent_id bigint,note text,updated_by_employee_id bigint,updated_by_employee_name text,updated_at timestamptz)
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  return query select n.tent_id,n.note,n.updated_by_employee_id,e.name,n.updated_at from public.tent_notes n left join public.employees e on e.id=n.updated_by_employee_id order by n.tent_id;
end $$;

create or replace function public.employee_save_tent_note(p_token text,p_tent_id bigint,p_note text)
returns void language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  if not exists(select 1 from public.tents where id=p_tent_id) then raise exception 'Teltet findes ikke'; end if;
  if btrim(coalesce(p_note,''))='' then delete from public.tent_notes where tent_id=p_tent_id;
  else insert into public.tent_notes(tent_id,note,updated_by_employee_id) values(p_tent_id,btrim(p_note),v_employee.employee_id)
    on conflict(tent_id) do update set note=excluded.note,updated_by_employee_id=excluded.updated_by_employee_id,updated_at=now(); end if;
end $$;

create or replace function public.employee_workshop_tasks(p_token text)
returns table(id bigint,tent_id bigint,tent_name text,booking_id bigint,booking_name text,description text,status text,completion_note text,created_by_employee_id bigint,created_by_employee_name text,completed_by_employee_id bigint,completed_by_employee_name text,created_at timestamptz,updated_at timestamptz,completed_at timestamptz)
language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  return query select w.id,w.tent_id,t.name,w.booking_id,coalesce(b.customer_name,b.title,b.order_no),w.description,w.status,w.completion_note,w.created_by_employee_id,ce.name,w.completed_by_employee_id,de.name,w.created_at,w.updated_at,w.completed_at
  from public.tent_workshop_tasks w join public.tents t on t.id=w.tent_id left join public.bookings b on b.id=w.booking_id left join public.employees ce on ce.id=w.created_by_employee_id left join public.employees de on de.id=w.completed_by_employee_id
  order by (w.status='open') desc,w.created_at desc,w.id desc;
end $$;

create or replace function public.employee_report_tent_damage(p_token text,p_tent_id bigint,p_booking_id bigint,p_description text)
returns bigint language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; v_id bigint; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  if btrim(coalesce(p_description,''))='' then raise exception 'Beskriv skaden'; end if;
  insert into public.tent_workshop_tasks(tent_id,booking_id,description,created_by_employee_id) values(p_tent_id,p_booking_id,btrim(p_description),v_employee.employee_id) returning id into v_id; return v_id;
end $$;

create or replace function public.employee_set_workshop_task_status(p_token text,p_task_id bigint,p_completed boolean,p_completion_note text default '')
returns void language plpgsql security definer set search_path = public, pg_temp
as $$ declare v_employee record; begin
  select * into v_employee from public.pala_session_employee(p_token) limit 1; if v_employee.employee_id is null then raise exception 'Medarbejderlogin kræves'; end if;
  update public.tent_workshop_tasks set status=case when p_completed then 'completed' else 'open' end,completion_note=case when p_completed then btrim(coalesce(p_completion_note,'')) else '' end,completed_by_employee_id=case when p_completed then v_employee.employee_id else null end,completed_at=case when p_completed then now() else null end,updated_at=now() where id=p_task_id;
  if not found then raise exception 'Systueopgaven findes ikke'; end if;
end $$;

-- Appen bruger et selvstændigt medarbejderlogin. Katalogdata kan læses af webappen,
-- mens alle ændringer går gennem validerede SECURITY DEFINER-funktioner.
alter table public.tents enable row level security;
alter table public.hardware enable row level security;
alter table public.inventory enable row level security;
alter table public.bookings enable row level security;
alter table public.booking_tents enable row level security;
alter table public.booking_inventory enable row level security;
alter table public.employees enable row level security;
alter table public.employee_credentials enable row level security;
alter table public.staffing_shifts enable row level security;
alter table public.staffing_assignments enable row level security;
alter table public.staffing_invitations enable row level security;
alter table public.tent_documents enable row level security;
alter table public.tent_images enable row level security;
alter table public.tent_notes enable row level security;
alter table public.tent_workshop_tasks enable row level security;
alter table public.tent_wet_status enable row level security;
alter table public.employee_sessions enable row level security;
alter table public.order_access_tokens enable row level security;
alter table public.order_checklist_progress enable row level security;

revoke all on all tables in schema public from anon, authenticated;
grant select on public.tents,public.hardware,public.inventory,public.bookings,public.booking_tents,public.booking_inventory,public.employees,public.staffing_shifts,public.staffing_assignments,public.tent_documents,public.tent_images to anon, authenticated;

drop policy if exists pala_read_tents on public.tents; create policy pala_read_tents on public.tents for select to anon,authenticated using(true);
drop policy if exists pala_read_hardware on public.hardware; create policy pala_read_hardware on public.hardware for select to anon,authenticated using(true);
drop policy if exists pala_read_inventory on public.inventory; create policy pala_read_inventory on public.inventory for select to anon,authenticated using(true);
drop policy if exists pala_read_bookings on public.bookings; create policy pala_read_bookings on public.bookings for select to anon,authenticated using(true);
drop policy if exists pala_read_booking_tents on public.booking_tents; create policy pala_read_booking_tents on public.booking_tents for select to anon,authenticated using(true);
drop policy if exists pala_read_booking_inventory on public.booking_inventory; create policy pala_read_booking_inventory on public.booking_inventory for select to anon,authenticated using(true);
drop policy if exists pala_read_employees on public.employees; create policy pala_read_employees on public.employees for select to anon,authenticated using(true);
drop policy if exists pala_read_shifts on public.staffing_shifts; create policy pala_read_shifts on public.staffing_shifts for select to anon,authenticated using(true);
drop policy if exists pala_read_assignments on public.staffing_assignments; create policy pala_read_assignments on public.staffing_assignments for select to anon,authenticated using(true);
drop policy if exists pala_read_documents on public.tent_documents; create policy pala_read_documents on public.tent_documents for select to anon,authenticated using(true);
drop policy if exists pala_read_images on public.tent_images; create policy pala_read_images on public.tent_images for select to anon,authenticated using(true);

revoke all on all functions in schema public from public;
grant execute on function public.employee_validate(text),public.employee_login(bigint,text),public.employee_logout(text),public.inventory_catalog_v1(),
  public.employee_change_own_pin(text,text,text),public.admin_save_employee(text,bigint,text,boolean),public.admin_change_employee_pin(text,bigint,text),public.admin_delete_employee(text,bigint),
  public.admin_save_booking(text,bigint,text,text,text,date,date,date,date,text,text,text,jsonb,jsonb),public.admin_delete_booking(text,bigint),public.admin_finish_booking(text,bigint),
  public.admin_save_shift_v2(text,bigint,bigint,date,time,time,integer,text,text,bigint),public.admin_delete_shift(text,bigint),public.employee_staff_signup(text,bigint),public.employee_staff_signoff(text,bigint),
  public.admin_invite_staffing(text,bigint,jsonb),public.employee_staffing_invitations(text),public.employee_respond_staffing_invitation(text,bigint,boolean),
  public.admin_save_tent_v2(text,bigint,text,text,integer,numeric,numeric,numeric,numeric,numeric,numeric,jsonb),public.admin_delete_tent(text,bigint),
  public.admin_save_inventory_v2(text,bigint,text,text,text,integer,text),public.admin_delete_inventory(text,bigint),
  public.admin_add_tent_image(text,bigint,text,text),public.admin_delete_tent_image(text,bigint),public.admin_add_tent_document(text,bigint,text,text,text,text),public.admin_delete_tent_document(text,bigint),
  public.employee_mark_tent_wet(text,bigint),public.employee_clear_tent_wet(text,bigint),public.employee_mark_tent_sides_wet(text,bigint),public.employee_clear_tent_sides_wet(text,bigint),public.admin_clear_tent_drying(text,bigint,integer),
  public.employee_order_check_token(text,bigint),public.order_checklist_get(text),public.order_checklist_change(text,bigint,text,integer,boolean),public.order_checklist_set_drying(text,bigint,integer,boolean),
  public.warehouse_stock_status_v2(),public.booking_checklist_summaries(),public.employee_tent_notes(text),public.employee_save_tent_note(text,bigint,text),public.employee_workshop_tasks(text),public.employee_report_tent_damage(text,bigint,bigint,text),public.employee_set_workshop_task_status(text,bigint,boolean,text)
to anon,authenticated;

do $$
declare v_table text;
begin
  foreach v_table in array array['tents','hardware','inventory','bookings','booking_tents','booking_inventory','employees','staffing_shifts','staffing_assignments','staffing_invitations','tent_documents','tent_images','tent_notes','tent_workshop_tasks','tent_wet_status','order_checklist_progress'] loop
    begin execute format('alter publication supabase_realtime add table public.%I',v_table); exception when duplicate_object then null; end;
  end loop;
end $$;

commit;
