-- PALA v100 · Lager, bemanding, notifikationer og systue
-- Installeres som én idempotent Supabase-migration.

create or replace function public.pala_v100_employee_id(p_token text, p_admin boolean default false)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_employee_id bigint;
begin
  select e.id into v_employee_id
  from public.employee_sessions s
  join public.employees e on e.id = s.employee_id
  where s.token = p_token
    and e.active is true
    and (s.expires_at is null or s.expires_at > now())
    and (not p_admin or e.is_admin is true)
  limit 1;
  if v_employee_id is null then
    raise exception 'Login er udløbet eller mangler de nødvendige rettigheder.';
  end if;
  return v_employee_id;
end;
$$;

alter table public.hardware
  add column if not exists category text not null default 'Standard hardware',
  add column if not exists material text not null default '',
  add column if not exists length_m numeric;

create table if not exists public.tent_parts (
  id bigint generated by default as identity primary key,
  tent_id bigint not null references public.tents(id) on delete cascade,
  name text not null,
  description text not null default '',
  qty integer not null default 1 check (qty > 0),
  optional boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.special_hardware (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  quantity_total integer not null default 0 check (quantity_total >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.special_hardware_tents (
  special_hardware_id bigint not null references public.special_hardware(id) on delete cascade,
  tent_id bigint not null references public.tents(id) on delete cascade,
  primary key (special_hardware_id, tent_id)
);

create table if not exists public.workshop_jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  customer_name text not null default '',
  address text not null default '',
  start_date date not null,
  end_date date not null,
  status text not null default 'Planlagt' check (status in ('Planlagt','I gang','Afsluttet','Annulleret')),
  color text not null default '#6C8EBF',
  notes text not null default '',
  created_by_employee_id bigint references public.employees(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create table if not exists public.workshop_job_documents (
  id bigint generated by default as identity primary key,
  workshop_job_id bigint not null references public.workshop_jobs(id) on delete cascade,
  title text not null,
  file_name text not null,
  mime_type text not null default 'application/octet-stream',
  file_data text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.staff_leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  leave_type text not null check (leave_type in ('Ferie','Ude')),
  start_date date not null,
  end_date date not null,
  status text not null default 'pending' check (status in ('pending','approved','declined')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  responded_by_employee_id bigint references public.employees(id) on delete set null,
  check (end_date >= start_date)
);

-- Realtime-signalet indeholder ingen forretningsdata. Det bruges kun til at bede
-- andre åbne PALA-enheder om at genindlæse de beskyttede data via deres RPC'er.
create table if not exists public.pala_sync_events (
  id bigint generated by default as identity primary key,
  source text not null,
  changed_at timestamptz not null default now()
);

create index if not exists tent_parts_tent_sort_idx
  on public.tent_parts(tent_id, sort_order, name);
create index if not exists special_hardware_tents_tent_idx
  on public.special_hardware_tents(tent_id, special_hardware_id);
create index if not exists workshop_jobs_period_idx
  on public.workshop_jobs(start_date, end_date, status);
create index if not exists workshop_job_documents_job_idx
  on public.workshop_job_documents(workshop_job_id, created_at);
create index if not exists staff_leave_requests_employee_period_idx
  on public.staff_leave_requests(employee_id, start_date, end_date, status);
create index if not exists staff_leave_requests_pending_idx
  on public.staff_leave_requests(created_at desc)
  where status = 'pending';
create index if not exists staff_leave_requests_responder_idx
  on public.staff_leave_requests(responded_by_employee_id)
  where responded_by_employee_id is not null;
create index if not exists workshop_jobs_creator_idx
  on public.workshop_jobs(created_by_employee_id)
  where created_by_employee_id is not null;

alter table public.tent_parts enable row level security;
alter table public.special_hardware enable row level security;
alter table public.special_hardware_tents enable row level security;
alter table public.workshop_jobs enable row level security;
alter table public.workshop_job_documents enable row level security;
alter table public.staff_leave_requests enable row level security;
alter table public.pala_sync_events enable row level security;

drop policy if exists "pala_sync_events_read" on public.pala_sync_events;
create policy "pala_sync_events_read"
  on public.pala_sync_events
  for select
  to anon
  using (true);

revoke all on table public.tent_parts from anon, authenticated;
revoke all on table public.special_hardware from anon, authenticated;
revoke all on table public.special_hardware_tents from anon, authenticated;
revoke all on table public.workshop_jobs from anon, authenticated;
revoke all on table public.workshop_job_documents from anon, authenticated;
revoke all on table public.staff_leave_requests from anon, authenticated;
revoke all on table public.pala_sync_events from anon, authenticated;
grant select on public.pala_sync_events to anon;

create or replace function public.pala_v100_emit_sync_event()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.pala_sync_events(source) values (tg_table_name);
  delete from public.pala_sync_events
  where changed_at < now() - interval '7 days';
  return null;
end;
$$;

revoke all on function public.pala_v100_emit_sync_event() from public, anon, authenticated;

do $$
declare t text;
begin
  foreach t in array array['tent_parts','special_hardware','special_hardware_tents','workshop_jobs','workshop_job_documents','staff_leave_requests'] loop
    execute format('drop trigger if exists pala_v100_sync_event on public.%I', t);
    execute format('create trigger pala_v100_sync_event after insert or update or delete on public.%I for each statement execute function public.pala_v100_emit_sync_event()', t);
  end loop;
end $$;

create or replace function public.employee_tent_parts(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.pala_v100_employee_id(p_token, false);
  return coalesce((select jsonb_agg(to_jsonb(p) order by p.tent_id, p.sort_order, p.name) from public.tent_parts p), '[]'::jsonb);
end;
$$;

create or replace function public.employee_special_hardware(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.pala_v100_employee_id(p_token, false);
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', h.id,
      'name', h.name,
      'description', h.description,
      'quantity_total', h.quantity_total,
      'updated_at', h.updated_at,
      'tent_ids', coalesce((select jsonb_agg(l.tent_id order by l.tent_id) from public.special_hardware_tents l where l.special_hardware_id = h.id), '[]'::jsonb),
      'tent_names', coalesce((select jsonb_agg(t.name order by t.name) from public.special_hardware_tents l join public.tents t on t.id = l.tent_id where l.special_hardware_id = h.id), '[]'::jsonb)
    ) order by h.name)
    from public.special_hardware h
  ), '[]'::jsonb);
end;
$$;

create or replace function public.admin_save_tent_parts(p_token text, p_tent_id bigint, p_parts jsonb)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.pala_v100_employee_id(p_token, true);
  if not exists (select 1 from public.tents where id = p_tent_id) then raise exception 'Teltet findes ikke.'; end if;
  delete from public.tent_parts where tent_id = p_tent_id;
  insert into public.tent_parts(tent_id, name, description, qty, optional, sort_order)
  select p_tent_id,
         trim(coalesce(x->>'name','')),
         coalesce(x->>'description',''),
         greatest(1, coalesce((x->>'qty')::integer,1)),
         coalesce((x->>'optional')::boolean,true),
         coalesce((x->>'sort_order')::integer,0)
  from jsonb_array_elements(coalesce(p_parts,'[]'::jsonb)) x
  where trim(coalesce(x->>'name','')) <> '';
end;
$$;

create or replace function public.admin_save_hardware_categories(p_token text, p_tent_id bigint, p_categories jsonb)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare x jsonb;
begin
  perform public.pala_v100_employee_id(p_token, true);
  for x in select * from jsonb_array_elements(coalesce(p_categories,'[]'::jsonb)) loop
    update public.hardware h
    set category = coalesce(nullif(trim(x->>'category'),''),'Standard hardware'),
        material = coalesce(x->>'material',''),
        length_m = nullif(x->>'length_m','')::numeric
    where h.tent_id = p_tent_id
      and case
        when nullif(x->>'id','') is not null then h.id = (x->>'id')::bigint
        else h.sort_order = coalesce((x->>'sort_order')::integer,0) and h.name = coalesce(x->>'name','')
      end;
  end loop;
end;
$$;

create or replace function public.admin_set_shift_assignments(p_token text,p_shift_id bigint,p_employee_ids bigint[])
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $$
begin
  perform public.pala_v100_employee_id(p_token,true);
  if not exists(select 1 from public.staffing_shifts where id=p_shift_id) then raise exception 'Vagten findes ikke.'; end if;
  delete from public.staffing_assignments a
  where a.shift_id=p_shift_id and not (a.employee_id=any(coalesce(p_employee_ids,'{}'::bigint[])));
  insert into public.staffing_assignments(shift_id,employee_id)
  select p_shift_id,e.id
  from public.employees e
  where e.active is true
    and e.id=any(coalesce(p_employee_ids,'{}'::bigint[]))
    and not exists(select 1 from public.staffing_assignments a where a.shift_id=p_shift_id and a.employee_id=e.id);
end;
$$;

create or replace function public.admin_configure_shift_staff(
  p_token text,
  p_shift_id bigint,
  p_direct_employee_ids bigint[],
  p_request_employee_ids bigint[]
)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_admin_id bigint;
  v_booking_id bigint;
begin
  v_admin_id:=public.pala_v100_employee_id(p_token,true);
  select booking_id into v_booking_id
  from public.staffing_shifts
  where id=p_shift_id;
  if not found then raise exception 'Vagten findes ikke.'; end if;

  delete from public.staffing_assignments a
  where a.shift_id=p_shift_id
    and not (a.employee_id=any(coalesce(p_direct_employee_ids,'{}'::bigint[])));

  insert into public.staffing_assignments(shift_id,employee_id)
  select p_shift_id,e.id
  from public.employees e
  where e.active is true
    and e.id=any(coalesce(p_direct_employee_ids,'{}'::bigint[]))
  on conflict do nothing;

  -- Direkte tilknytning og "ikke valgt" må ikke efterlade en gammel forespørgsel.
  delete from public.staffing_invitations i
  where i.shift_id=p_shift_id
    and (
      i.employee_id=any(coalesce(p_direct_employee_ids,'{}'::bigint[]))
      or not (i.employee_id=any(coalesce(p_request_employee_ids,'{}'::bigint[])))
    );

  insert into public.staffing_invitations(
    booking_id,shift_id,employee_id,status,created_by_employee_id,created_at,responded_at
  )
  select v_booking_id,p_shift_id,e.id,'pending',v_admin_id,now(),null
  from public.employees e
  where e.active is true
    and e.id=any(coalesce(p_request_employee_ids,'{}'::bigint[]))
    and not (e.id=any(coalesce(p_direct_employee_ids,'{}'::bigint[])))
  on conflict(shift_id,employee_id) do update
    set booking_id=excluded.booking_id,
        status='pending',
        created_by_employee_id=excluded.created_by_employee_id,
        created_at=now(),
        responded_at=null;
end;
$$;

create or replace function public.employee_delete_staffing_notification(p_token text,p_invitation_id bigint)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_employee_id bigint;
begin
  v_employee_id:=public.pala_v100_employee_id(p_token,false);
  delete from public.staffing_invitations i where i.id=p_invitation_id and i.employee_id=v_employee_id and i.status<>'pending';
end;
$$;

create or replace function public.employee_delete_leave_notification(p_token text,p_request_id bigint)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_employee_id bigint;
begin
  v_employee_id:=public.pala_v100_employee_id(p_token,false);
  delete from public.staff_leave_requests r
  where r.id=p_request_id
    and r.employee_id=v_employee_id
    and r.status<>'pending';
end;
$$;

create or replace function public.employee_cleanup_staffing_notifications(p_token text)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_employee_id bigint;
begin
  v_employee_id:=public.pala_v100_employee_id(p_token,false);
  delete from public.staffing_invitations i
  where i.employee_id=v_employee_id
    and i.status='pending'
    and exists(
      select 1 from public.staffing_shifts s
      where s.id=i.shift_id
        and (select count(*) from public.staffing_assignments a where a.shift_id=s.id)>=s.workers_needed
    );
end;
$$;

create or replace function public.employee_request_leave(p_token text,p_leave_type text,p_start_date date,p_end_date date)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_employee_id bigint;v_id bigint;
begin
  v_employee_id:=public.pala_v100_employee_id(p_token,false);
  if p_leave_type not in ('Ferie','Ude') or p_start_date is null or p_end_date is null or p_end_date<p_start_date then raise exception 'Fraværsperioden er ugyldig.'; end if;
  if exists(select 1 from public.staff_leave_requests r where r.employee_id=v_employee_id and r.status='pending' and r.start_date<=p_end_date and r.end_date>=p_start_date) then raise exception 'Du har allerede en afventende anmodning i perioden.'; end if;
  insert into public.staff_leave_requests(employee_id,leave_type,start_date,end_date) values(v_employee_id,p_leave_type,p_start_date,p_end_date) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.employee_leave_requests(p_token text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp
as $$
declare v_employee_id bigint;
begin
  v_employee_id:=public.pala_v100_employee_id(p_token,false);
  return coalesce((select jsonb_agg(to_jsonb(r) order by r.created_at desc) from public.staff_leave_requests r where r.employee_id=v_employee_id),'[]'::jsonb);
end;
$$;

create or replace function public.admin_leave_requests(p_token text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp
as $$
begin
  perform public.pala_v100_employee_id(p_token,true);
  return coalesce((select jsonb_agg(to_jsonb(r)||jsonb_build_object('employee_name',e.name) order by r.created_at desc) from public.staff_leave_requests r join public.employees e on e.id=r.employee_id where r.status='pending'),'[]'::jsonb);
end;
$$;

create or replace function public.admin_respond_leave_request(p_token text,p_request_id bigint,p_approve boolean)
returns void language plpgsql security definer set search_path=public,pg_temp
as $$
declare
  v_admin_id bigint;
  v_request public.staff_leave_requests%rowtype;
  v_employee_name text;
  v_marker text;
begin
  v_admin_id:=public.pala_v100_employee_id(p_token,true);
  select * into v_request
  from public.staff_leave_requests
  where id=p_request_id and status='pending'
  for update;
  if not found then raise exception 'Fraværsanmodningen findes ikke eller er allerede besvaret.'; end if;

  if p_approve then
    select name into v_employee_name from public.employees where id=v_request.employee_id;
    v_marker:=format(
      '[PALA-FRAVAER employee=%s end=%s type=%s]',
      v_request.employee_id,
      v_request.end_date,
      v_request.leave_type
    );
    if not exists (
      select 1 from public.staffing_shifts s
      where s.notes like '%'||v_marker||'%'
    ) then
      insert into public.staffing_shifts(
        booking_id,shift_date,start_time,end_time,workers_needed,title,notes,
        daily_leader_employee_id,created_by_employee_id
      ) values (
        null,v_request.start_date,null,null,1,
        v_request.leave_type||' · '||coalesce(v_employee_name,'Medarbejder'),
        v_marker,null,v_admin_id
      );
    end if;
  end if;

  update public.staff_leave_requests
  set status=case when p_approve then 'approved' else 'declined' end,
      responded_at=now(),
      responded_by_employee_id=v_admin_id
  where id=p_request_id;
end;
$$;

create or replace function public.admin_save_special_hardware(
  p_token text,
  p_id bigint,
  p_name text,
  p_description text,
  p_quantity_total integer,
  p_tent_ids bigint[]
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_id bigint;
begin
  perform public.pala_v100_employee_id(p_token, true);
  if trim(coalesce(p_name,'')) = '' then raise exception 'Navn mangler.'; end if;
  if p_id is null then
    insert into public.special_hardware(name,description,quantity_total)
    values(trim(p_name),coalesce(p_description,''),greatest(0,coalesce(p_quantity_total,0))) returning id into v_id;
  else
    update public.special_hardware set name=trim(p_name),description=coalesce(p_description,''),quantity_total=greatest(0,coalesce(p_quantity_total,0)),updated_at=now() where id=p_id returning id into v_id;
    if v_id is null then raise exception 'Specialhardwaren findes ikke.'; end if;
  end if;
  delete from public.special_hardware_tents where special_hardware_id=v_id;
  insert into public.special_hardware_tents(special_hardware_id,tent_id)
  select v_id, id from public.tents where id = any(coalesce(p_tent_ids,'{}'::bigint[]));
  return v_id;
end;
$$;

create or replace function public.admin_link_special_hardware_to_tent(p_token text, p_tent_id bigint, p_special_ids bigint[])
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.pala_v100_employee_id(p_token, true);
  delete from public.special_hardware_tents where tent_id=p_tent_id;
  insert into public.special_hardware_tents(special_hardware_id,tent_id)
  select id,p_tent_id from public.special_hardware where id = any(coalesce(p_special_ids,'{}'::bigint[]));
end;
$$;

create or replace function public.admin_delete_special_hardware(p_token text, p_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$ begin perform public.pala_v100_employee_id(p_token,true); delete from public.special_hardware where id=p_id; end $$;

create or replace function public.employee_workshop_jobs(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.pala_v100_employee_id(p_token,false);
  return coalesce((select jsonb_agg(to_jsonb(j) order by j.start_date,j.title) from public.workshop_jobs j), '[]'::jsonb);
end;
$$;

create or replace function public.employee_workshop_job_documents(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.pala_v100_employee_id(p_token,false);
  return coalesce((select jsonb_agg(jsonb_build_object('id',d.id,'workshop_job_id',d.workshop_job_id,'title',d.title,'file_name',d.file_name,'mime_type',d.mime_type,'created_at',d.created_at) order by d.created_at) from public.workshop_job_documents d), '[]'::jsonb);
end;
$$;

create or replace function public.employee_workshop_job_document(p_token text, p_id bigint)
returns table(title text,file_name text,mime_type text,file_data text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.pala_v100_employee_id(p_token,false);
  return query select d.title,d.file_name,d.mime_type,d.file_data from public.workshop_job_documents d where d.id=p_id;
end;
$$;

create or replace function public.admin_save_workshop_job(
  p_token text,
  p_id bigint,
  p_title text,
  p_customer_name text,
  p_address text,
  p_start_date date,
  p_end_date date,
  p_status text,
  p_color text,
  p_notes text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_employee_id bigint; v_id bigint;
begin
  v_employee_id:=public.pala_v100_employee_id(p_token,true);
  if trim(coalesce(p_title,''))='' then raise exception 'Jobnavn mangler.'; end if;
  if p_start_date is null or p_end_date is null or p_end_date<p_start_date then raise exception 'Datoerne er ugyldige.'; end if;
  if p_id is null then
    insert into public.workshop_jobs(title,customer_name,address,start_date,end_date,status,color,notes,created_by_employee_id)
    values(trim(p_title),coalesce(p_customer_name,''),coalesce(p_address,''),p_start_date,p_end_date,coalesce(nullif(p_status,''),'Planlagt'),coalesce(nullif(p_color,''),'#6C8EBF'),coalesce(p_notes,''),v_employee_id)
    returning id into v_id;
  else
    update public.workshop_jobs set title=trim(p_title),customer_name=coalesce(p_customer_name,''),address=coalesce(p_address,''),start_date=p_start_date,end_date=p_end_date,status=coalesce(nullif(p_status,''),'Planlagt'),color=coalesce(nullif(p_color,''),'#6C8EBF'),notes=coalesce(p_notes,''),updated_at=now() where id=p_id returning id into v_id;
    if v_id is null then raise exception 'Systuejobbet findes ikke.'; end if;
  end if;
  return v_id;
end;
$$;

create or replace function public.admin_delete_workshop_job(p_token text,p_id bigint)
returns void language plpgsql security definer set search_path=public,pg_temp
as $$ begin perform public.pala_v100_employee_id(p_token,true); delete from public.workshop_jobs where id=p_id; end $$;

create or replace function public.admin_add_workshop_job_document(p_token text,p_workshop_job_id bigint,p_title text,p_file_name text,p_mime_type text,p_file_data text)
returns bigint language plpgsql security definer set search_path=public,pg_temp
as $$
declare v_id bigint;
begin
  perform public.pala_v100_employee_id(p_token,true);
  insert into public.workshop_job_documents(workshop_job_id,title,file_name,mime_type,file_data)
  values(p_workshop_job_id,trim(p_title),p_file_name,coalesce(p_mime_type,'application/octet-stream'),p_file_data) returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.admin_delete_workshop_job_document(p_token text,p_id bigint)
returns void language plpgsql security definer set search_path=public,pg_temp
as $$ begin perform public.pala_v100_employee_id(p_token,true); delete from public.workshop_job_documents where id=p_id; end $$;

revoke all on function public.pala_v100_employee_id(text,boolean) from public, anon, authenticated;

revoke all on function public.employee_tent_parts(text) from public, anon, authenticated;
revoke all on function public.employee_special_hardware(text) from public, anon, authenticated;
revoke all on function public.admin_save_tent_parts(text,bigint,jsonb) from public, anon, authenticated;
revoke all on function public.admin_save_hardware_categories(text,bigint,jsonb) from public, anon, authenticated;
revoke all on function public.admin_save_special_hardware(text,bigint,text,text,integer,bigint[]) from public, anon, authenticated;
revoke all on function public.admin_link_special_hardware_to_tent(text,bigint,bigint[]) from public, anon, authenticated;
revoke all on function public.admin_delete_special_hardware(text,bigint) from public, anon, authenticated;
revoke all on function public.employee_workshop_jobs(text) from public, anon, authenticated;
revoke all on function public.employee_workshop_job_documents(text) from public, anon, authenticated;
revoke all on function public.employee_workshop_job_document(text,bigint) from public, anon, authenticated;
revoke all on function public.admin_save_workshop_job(text,bigint,text,text,text,date,date,text,text,text) from public, anon, authenticated;
revoke all on function public.admin_delete_workshop_job(text,bigint) from public, anon, authenticated;
revoke all on function public.admin_add_workshop_job_document(text,bigint,text,text,text,text) from public, anon, authenticated;
revoke all on function public.admin_delete_workshop_job_document(text,bigint) from public, anon, authenticated;
revoke all on function public.admin_set_shift_assignments(text,bigint,bigint[]) from public, anon, authenticated;
revoke all on function public.admin_configure_shift_staff(text,bigint,bigint[],bigint[]) from public, anon, authenticated;
revoke all on function public.employee_delete_staffing_notification(text,bigint) from public, anon, authenticated;
revoke all on function public.employee_delete_leave_notification(text,bigint) from public, anon, authenticated;
revoke all on function public.employee_cleanup_staffing_notifications(text) from public, anon, authenticated;
revoke all on function public.employee_request_leave(text,text,date,date) from public, anon, authenticated;
revoke all on function public.employee_leave_requests(text) from public, anon, authenticated;
revoke all on function public.admin_leave_requests(text) from public, anon, authenticated;
revoke all on function public.admin_respond_leave_request(text,bigint,boolean) from public, anon, authenticated;

grant execute on function public.employee_tent_parts(text) to anon;
grant execute on function public.employee_special_hardware(text) to anon;
grant execute on function public.admin_save_tent_parts(text,bigint,jsonb) to anon;
grant execute on function public.admin_save_hardware_categories(text,bigint,jsonb) to anon;
grant execute on function public.admin_save_special_hardware(text,bigint,text,text,integer,bigint[]) to anon;
grant execute on function public.admin_link_special_hardware_to_tent(text,bigint,bigint[]) to anon;
grant execute on function public.admin_delete_special_hardware(text,bigint) to anon;
grant execute on function public.employee_workshop_jobs(text) to anon;
grant execute on function public.employee_workshop_job_documents(text) to anon;
grant execute on function public.employee_workshop_job_document(text,bigint) to anon;
grant execute on function public.admin_save_workshop_job(text,bigint,text,text,text,date,date,text,text,text) to anon;
grant execute on function public.admin_delete_workshop_job(text,bigint) to anon;
grant execute on function public.admin_add_workshop_job_document(text,bigint,text,text,text,text) to anon;
grant execute on function public.admin_delete_workshop_job_document(text,bigint) to anon;
grant execute on function public.admin_set_shift_assignments(text,bigint,bigint[]) to anon;
grant execute on function public.admin_configure_shift_staff(text,bigint,bigint[],bigint[]) to anon;
grant execute on function public.employee_delete_staffing_notification(text,bigint) to anon;
grant execute on function public.employee_delete_leave_notification(text,bigint) to anon;
grant execute on function public.employee_cleanup_staffing_notifications(text) to anon;
grant execute on function public.employee_request_leave(text,text,date,date) to anon;
grant execute on function public.employee_leave_requests(text) to anon;
grant execute on function public.admin_leave_requests(text) to anon;
grant execute on function public.admin_respond_leave_request(text,bigint,boolean) to anon;

do $$
declare t text;
begin
  foreach t in array array['tent_parts','special_hardware','special_hardware_tents','workshop_jobs','workshop_job_documents','staff_leave_requests','pala_sync_events'] loop
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then
      execute format('alter publication supabase_realtime add table public.%I',t);
    end if;
  end loop;
end $$;
