-- PALA v239 · files attached to orders
-- Applied to Supabase project zlnzmdxffjxjdijzyuwx on 2026-09-18.

create table if not exists public.booking_documents (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  title text not null,
  file_name text not null,
  mime_type text not null default 'application/octet-stream',
  file_data text not null,
  created_at timestamptz not null default now()
);

alter table public.booking_documents enable row level security;

create index if not exists booking_documents_booking_id_created_at_idx
  on public.booking_documents (booking_id, created_at, id);

create or replace function public.employee_booking_documents(p_token text, p_booking_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.pala_v100_employee_id(p_token,false);
  if not exists (select 1 from public.bookings b where b.id=p_booking_id) then
    raise exception 'Ordren findes ikke.';
  end if;
  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'id',d.id,
        'booking_id',d.booking_id,
        'title',d.title,
        'file_name',d.file_name,
        'mime_type',d.mime_type,
        'created_at',d.created_at
      )
      order by d.created_at,d.id
    )
    from public.booking_documents d
    where d.booking_id=p_booking_id
  ),'[]'::jsonb);
end;
$$;

create or replace function public.employee_booking_document(p_token text, p_id bigint)
returns table(title text,file_name text,mime_type text,file_data text)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.pala_v100_employee_id(p_token,false);
  return query
    select d.title,d.file_name,d.mime_type,d.file_data
    from public.booking_documents d
    where d.id=p_id;
end;
$$;

create or replace function public.admin_add_booking_document(
  p_token text,
  p_booking_id bigint,
  p_title text,
  p_file_name text,
  p_mime_type text,
  p_file_data text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare v_id bigint;
begin
  perform public.pala_v100_employee_id(p_token,true);
  if not exists (select 1 from public.bookings b where b.id=p_booking_id) then
    raise exception 'Ordren findes ikke.';
  end if;
  if coalesce(length(p_file_data),0)=0 then
    raise exception 'Filen er tom.';
  end if;
  insert into public.booking_documents(booking_id,title,file_name,mime_type,file_data)
  values(
    p_booking_id,
    coalesce(nullif(trim(p_title),''),p_file_name,'Fil'),
    coalesce(nullif(p_file_name,''),'fil'),
    coalesce(nullif(p_mime_type,''),'application/octet-stream'),
    p_file_data
  )
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.admin_delete_booking_document(p_token text,p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.pala_v100_employee_id(p_token,true);
  delete from public.booking_documents where id=p_id;
end;
$$;

revoke all on function public.employee_booking_documents(text,bigint) from public;
revoke all on function public.employee_booking_document(text,bigint) from public;
revoke all on function public.admin_add_booking_document(text,bigint,text,text,text,text) from public;
revoke all on function public.admin_delete_booking_document(text,bigint) from public;

grant execute on function public.employee_booking_documents(text,bigint) to anon,authenticated;
grant execute on function public.employee_booking_document(text,bigint) to anon,authenticated;
grant execute on function public.admin_add_booking_document(text,bigint,text,text,text,text) to anon,authenticated;
grant execute on function public.admin_delete_booking_document(text,bigint) to anon,authenticated;
